//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VenadoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public int producto { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public double precio { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual producto producto1 { get; set; }
    }
}
