//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VenadoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_factura
    {
        public int factura { get; set; }
        public int cantidad { get; set; }
        public int producto { get; set; }
        public double precio { get; set; }
        public Nullable<double> total { get; set; }
    
        public virtual enc_factura enc_factura { get; set; }
        public virtual producto producto1 { get; set; }
    }
}
